#!/bin/sh

xset r rate 180 55 &
xset s 0 0 &
xset dpms 0 0 0 &
# xset s 300 300 &
# xset dpms 300 300 300 &

# FIXME: test if DVI-D-0 exists
xrandr --output HDMI-0 --primary --mode 1920x1080 --right-of DVI-D-0

if command -v pulsemixer;
then
  pulsemixer --max-volume 100
fi

# mpd &
dunst &
hsetroot -fill ~/data/pics/mountain-deers.jpg &
# hsetroot -solid black &
xcompmgr &
redshift &
dwmblocks &
# wal -R &

unclutter --timeout 2 &

# restore-colorscheme

# # Fixes slow Telegram startup
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

exec dwm

