#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Command shortcuts.
alias \
	yda="yt-dlp -x --audio-quality 0 --add-metadata -i" \
	mc="mc --nosubshell" \
	octave="octave -q" \
	z="setsid zathura" \
	cn="create-note"

# This is needed to be able to run aliases with sudo/doas
alias \
	doas="doas " \
	sudo="sudo "

if [ -x "$(command -v todo.sh)" ];
then
	alias t="todo.sh"
elif [ -x "$(command -v todo-txt)" ];
then
	alias t="todo-txt"
fi

# Verbosity and interactivity.
alias \
	bc="bc -ql"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	pacman="pacman --color=auto" \
	yay="yay --color=auto"

# Folders
alias \
	c="cd ~/.config && ls" \
	gnc="cd $XDG_CONFIG_HOME/nvim && nvim ."

# $HOME cleanup
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"'
alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings'

