#!/bin/sh

source "$HOME/.config/shell/env"

# export EDITOR="vim"
# export TERMINAL="st"
# export BROWSER="firefox"

# # XDG
# export XDG_STATE_HOME="$HOME/.local/state"
# export XDG_DATA_HOME="$HOME/.local/share"
# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_CACHE_HOME="$HOME/.cache"

# # $PATH population
# export GOPATH="$XDG_DATA_HOME"/go
# export PATH="$PATH:$GOPATH/bin"

# # Adds `~/.local/bin` to $PATH
# local bin_dirs=$(find ~/.local/bin -type d -printf :%p)
# export PATH="${PATH}${bin_dirs}"
# #export PATH="${PATH}:$HOME/.local/bin:$HOME/.local/bin/scripts:$HOME/.local/bin/scripts/music"

# # $HOME cleanup
# export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
# export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
# export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
# export LESSHISTFILE="$XDG_CACHE_HOME"/less/history

# export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
# export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
# export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

